apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-ingestion
  name: location-ingestion
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: location-ingestion
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-ingestion
  name: location-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-ingestion
  template:
    metadata:
      labels:
        service: location-ingestion
    spec:
      containers:
      - image: location-ingestion:latest
        name: location-ingestion
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "location_topic"
      restartPolicy: Always
