apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-processor
  name: location-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-processor
  template:
    metadata:
      labels:
        service: location-processor
    spec:
      containers:
      - image: location-processor:latest
        name: location-processor
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "location_topic"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
